theme: jekyll-theme-minimal
author: Mohamed Anouar HRAIRI
title: Mohamed Anouar HRAIRI's resume
description: Natural problem solver with strong interpersonal skills and a degree in computer software. Seeking a challenging opportunity to develop and manage large projects where my advanced skills, education and couple years of experience can be fully utilized.
